[project]
name = "brandai-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "pymongo>=4.15.5",
    "python-dotenv>=1.2.1",
    "python-json-logger>=4.0.0",
    "uvicorn>=0.40.0",
]
